### ISSUE TITLE
eCommerce criterias suggestion

### ISSUE THREAD

**Issue by nicomollet** [comparewp/comparewp#10]
Hello,

I recenlty added WooCommerce info but I found out the eCommerce spreadsheet https://docs.google.com/spreadsheet/ccc?key=0AoY8IFUX301qdENFS0x2RkdEclpxWHBoUGlQbUlHZUE needed a lot more criterias.
Here is the almost complete list of criterias I think would benefit our comparison charts.
- Basic info
  - Developer Confirmation that the information in this spreadsheet is correct
  - Cost
  - Free support available
  - Paid support available
  - Current team size
  - Lead Developer
  - Team contributes back to core
  - Github repo
  - First release date
  - Supported WP version
  - Has UI?
  - Uses CPT for products
  - Works on regular themes
  - Use shortcodes
  - Free upgrades
  - Google Analytics integration
  - On WP.org repo
  - Theme showcase for exclusively designed themes
  - Additional tables created on DB
- Type of Products it Sells
  - Physical
  - Digital
  - Subscriptions
  - Services
  - Variable product
- Products managment
  - Manage stock
  - Low stock notification
  - Out of stock notification
  - SKU identifier
  - Allow backorders
  - Linked products
  - Cross-Sells
  - Group products
  - Custom fields/attributes (ex: color)
  - Price changing product variations
  - Product bundles
  - Product reviews
  - Tax calculation
  - Product gallery
  - Category and tags
- Orders/Reports
  - Manage orders
  - Manage customers
  - Add notes
  - Sales report
  - Coupons report
  - Customers report
  - Stock report
- Sales/Discounts/Coupons
  - Sale price
  - Schedule sale
  - Cart discount coupon
  - Product discount coupon
  - Free shipping coupon
  - Volume/Number discount
- Shipping
  - Weight shipping
  - Table rate shipping
  - Live UPS rate
  - Live USPS rate
  - Live FedEx rate
- Payment
  - Support extra Payment Gateways through extension
  - Cheque
  - Bank transfer
  - Cash on delivery
  - Recurring payment/subscription
  - Paypal
  - Paypal Pro
  - Authorize
  - Google Checkout
  - Stripe
  - Braintree
- Emails
  - New order email
  - Processing order email
  - Completed order email
  - Customer invoice email
  - Customer note email
  - New account email
  - Customize html
- Integration
  - Google Analytics
  - ShareThis
  - ShareYourCart
  - Mailchimp
- Widgets
  - Best sellers
  - Cart
  - Featured products
  - Attribute filter search
  - On sale products
  - Price filter search
  - Product categories
  - Product search
  - Product tags
  - Random products
  - Recently viewed
  - Recent products
  - Recent reviews
  - Top rated products
- International/Localization
  - Localized text
  - Multi-Currency
  - Exclude countries
  - Multi-weight/dimensions unit
  - WPML compatibility
- Security
  - Force SSL on checkout
  - Enable guest checkout

What do you think, is it too much criterias?

**Comment by sc0ttkclark** [comment]
I think that may be too detailed, but once we have the new site going then this might be more easier to manage and beneficial (search/filters).

**Comment by nicomollet** [comment]
Nice, OK, let me know if I can help with the new website.
